apiVersion: v1
kind: Secret
metadata:
  name: blog
  labels:
    app: demo
type: Opaque
stringData:
  password: 5ecur3
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-xfusion
  labels:
    app: xfusion
spec:
  containers:
  - name: secret-container-xfusion
    image: fedora:latest
    command: ["/bin/sh", "-c", "sleep 360"]
    env:
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: blog
          key: password