apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nautilus
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual  
  hostPath:
    path: /mnt/itadmin
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nautilus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi 
  storageClassName: manual 
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-nautilus
  labels:
    app: nautilus
spec:
  containers:
  - name: container-nautilus
    image: httpd:latest
    ports:
    - containerPort: 80
    volumeMounts:
    - name: nautilus-volume
      mountPath: /usr/local/apache2/htdocs
  volumes:
  - name: nautilus-volume
    persistentVolumeClaim:
      claimName: pvc-nautilus
---
apiVersion: v1
kind: Service
metadata:
  name: web-nautilus
spec:
  type: NodePort
  selector:
    app: nautilus
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30008
